### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by focussing** [chjj/n64#1]
Hi!

the following is shown in the console 
`macbook:node raymond$ npm install n64 --save

> n64@0.0.5 install /Users/raymond/stack/node/node_modules/n64
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: *** No rule to make target `Release/obj.target/n64/src/int64.o', needed by `Release/n64.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/raymond/.nvm/versions/node/v4.6.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/raymond/.nvm/versions/node/v4.6.2/bin/node" "/Users/raymond/.nvm/versions/node/v4.6.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/raymond/stack/node/node_modules/n64
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
npm WARN node@1.0.0 No description
npm WARN node@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n64@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the n64@0.0.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the n64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs n64
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls n64
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raymond/.npm/_logs/2017-06-15T10_47_08_571Z-debug.log
macbook:node raymond$ 
`

**Comment by focussing** [comment]
Can I use n64 also outside of nodejs? For example only include the .js file?

**Comment by come-maiz** [comment]
Same problem here in ubuntu 16.04
node v6.10.2
npm  v3.10.10

The error doesn't say anything useful related to the cause. Any idea?

**Comment by chjj** [comment]
Should be fixed. @focussing, the JS file should be copy & pasteable if you add your own `assert` function.

**Comment by focussing** [comment]
Thanks for fixing!
I have a great node.js application - the only one so far that does the calculations right.
However I can't get it working. Included an assert.js file but that required more functions.
Included those but finally it gets stuck at an inherits.js file.

https://github.com/defunctzombie/commonjs-assert

Can you help me please?

**Comment by come-maiz** [comment]
Thanks @chjj, but mine still fails:

```
[...]
> n64@0.0.7 install /home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/src/node_modules/n64
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/src/node_modules/n64) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/install/lib/node_modules/npm/node_modules/node-gyp/lib/configu
re.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-71-generic
gyp ERR! command "/home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/install/bin/node" "/home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/install/lib/node_mo
dules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/src/node_modules/n64
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
bcoin@1.0.0-beta.12 /home/ubuntu/workspace/bcoin-org/bcoin/parts/bcoin/src
```

It's a little different, instead of complaining about make, it complains about binding.gyp. Should I open a different issue? I'm sorry, but I don't know much about node, so I'm lost with this cryptic errors.

**Comment by focussing** [comment]
Hi again!

I am only using a few numbers, would that help in making a "custom" assert.js so I would end up with only a few .js files?

```
var PIN = [0x31, 0x32, 0x33, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]; // ('1234')
var PINprime = Int64(0x3bb487ad);
var PINrnd = Int64.fromString('5e6a8e9a4115022b', false, 16);
var lowWordMask = Int64.fromString('00000000ffffffff', false, 16);

for (var i = 0; i < 12; i++) {
    var pin = Int64.from(PIN[i], false);
    PINrnd = PINrnd.xor(pin);
    var a = PINrnd.and(lowWordMask);
    a.imul(PINprime);

    var b = PINrnd.shr(Int64.from(32, false));

    PINrnd = a.xor(b);
}

console.log('result:', PINrnd.toString(16));

```

**Comment by focussing** [comment]
Seems that assert is a helper function, so I did this...
My calculations still work, but what could go wrong?

// var assert = require('assert');
var assert = function(e) {
    return true;
}
